### ISSUE TITLE
Wildcard Tokens with a lot of images don't fit on the page.

### ISSUE THREAD

**Issue by sammyp03** [TheNekoMomo/Momos-Token-Changer#11]
As title. Would be nice to have a scroll bar for tokens with a lot of images. 
![image](https://user-images.githubusercontent.com/71460138/226680289-7a9f138b-d9d8-488f-9ec4-316bf6a3ee44.png)

**Comment by TheNekoMomo** [comment]
Used to be one dont know why it stoped working

**Comment by TheNekoMomo** [comment]
Fixed in V0.1.6 thx for letting us know
