### ISSUE TITLE
Feature Request: Token HUD Wildcard per-image resizing

### ISSUE THREAD

**Issue by GambetTV** [TheNekoMomo/Momos-Token-Changer#6]
Hi, you posted on the Token HUD Wildcard github page saying your version has all the same features. So far I really like your version, but it does seem to be missing one of the most critical features of Token HUD Wildcard, which is the ability to add a little code to individual image's filenames that the module would use to make sizing alterations to it.

The format for this was "`_height#_scale#_`" so for instance one of my token images might be named JesseBarbarian1_scale1.5_.png and another would be named JesseBarbarian2_scale1.2_.png and the module would automatically recognize that the first image should have a scale of 1.5, and the second should have a scale of 1.2.

Your module is extremely needed among those of us who make use of Token HUD Wildcard, but I have THOUSANDS of token images that use this format, which at least for the moment your module doesn't seem to have this feature. Please add this if you're able to.

**Comment by TheNekoMomo** [comment]
Sorry the documentation is not up to date but I have already added the height and width part in with the name tho did not do scale, what did that one do?

**Comment by GambetTV** [comment]
If you go into the "Appearance" tab in a Token Configuration, you can see there's a value called "Scale (Ratio)". Width/Height changes the amount of squares a token takes up, whereas scale lets you size up or down a token within its square. So for instance you could make a token with a Width/Height of 1x1, with a scale of 2, appear to take up 2x2.

The reason this is so critical for me, is because I use miniature-esque top down tokens, and this module allows me to size tokens with very different dimensions to appear of the same size.

So for instance, in this screenshot below, both tokens are VERY different scales, with the token on the left being scale 1.6, while the token on the right is scale 1. But they wind up looking about the same size, letting me to very clever things with token images as a result.

![image](https://user-images.githubusercontent.com/72000497/225384805-f9931fe8-9bbf-4ac9-9e34-1902061bbf15.png)

**Comment by GambetTV** [comment]
Hi, I tested it out, scale doesn't seem to be working. Also I'm noticing something strange about height/width. These do seem to be working, however, if you have height/width set on one token, you need to have it set for ALL tokens, as setting it for one token seems to change the default for all tokens after that. The original module seemed to look at your Dimensions and Scale in the Prototype Token, and default the token to this value every time you changed tokens, unless the token's filename overrode this.

So for instance, if a prototype token was set to Width 1, Height 1, Scale 1, and then you had two tokens, one named Bob.png and one named Bob_width2_height2_scale1.3_.png, when you switched to Bob_width2_height2_scale1.3_.png it'd change the token to having a height/width of 2 and a scale of 1.3, and then if you switched to the Bob.png token, because there was nothing in the file name, it would default back to what was set in the Prototype Token. This was super convenient, because if you had a bunch of tokens that are largely the same size you could just have a default set to the prototype token, and only change the ones that needed to be changed.

Anyway though, that said, unless I'm doing it wrong setting scale doesn't do anything.

**Comment by TheNekoMomo** [comment]
I will look in to it, sorry

**Comment by TheNekoMomo** [comment]
The sacle should now be working, tho going to take a bit more work to get the token to go back to its default size when not specified in the file name
