### ISSUE TITLE
Feature Request: Make change size HUD button optional?

### ISSUE THREAD

**Issue by GambetTV** [TheNekoMomo/Momos-Token-Changer#9]
When you right click a token you have two add-on buttons, one to change the token art, and one to change the size of the token. I don't think I've ever needed something like this, so the button just kind of takes up space, and I have enough modules that there's already so many buttons on tokens that it really just clutters things up. Any way you could put it in the settings to turn this button off for GM users?

**Comment by TheNekoMomo** [comment]
Added a setting for each user so they can disable the button if they wish
